services:
  hysteria2:
    image: tobyxdd/hysteria:v2
    container_name: hysteria2
    restart: always
    network_mode: host
    volumes:
      - ./config.yaml:/etc/hysteria/config.yaml
      - /root/3x-ui/cert/cert.pem:/etc/hysteria/cert.pem:ro
      - /root/3x-ui/cert/private.key:/etc/hysteria/private.key:ro
    command: ["server", "-c", "/etc/hysteria/config.yaml"]
